### ISSUE TITLE
any pruned models available?

### ISSUE THREAD

**Issue by qianguih** [yihui-he/channel-pruning#1]
Hi Yihui,

Nice work on channel pruning! I am wondering is there any plan to release some pruned models? It would be really great for fast test. : )

**Comment by yihui-he** [comment]
we've released pruned VGG-16 3C 4X model:  https://github.com/yihui-he/channel-pruning/releases/tag/VGG-16_3C4x


model | Speed-up | Top-5 | Top-1
:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:
VGG-16 |4x            |  89.8904 | 70.574

Feel free to test them and leave your comments.

**Comment by qianguih** [comment]
It looks great. Thank you!

**Comment by yihui-he** [comment]
FYI, more models are released: https://github.com/yihui-he/channel-pruning/releases
