### ISSUE TITLE
Crashing while creating file `frozen500.pickle`

### ISSUE THREAD

**Issue by ddfabbro** [yihui-he/channel-pruning#104]
I'm following the example found in the `README`, but during step 2
```
python3 train.py -action c3 -caffe 0
```
my computer crashes.

The last generated file is `frozen500.pickle` with size of 5Gb.

What is causing this? Maybe I could lower memory usage?

**Comment by yihui-he** [comment]
You can sample less patches if you don't have enough memory. 
set `nBatches` in `lib/cfgs.py` to like 100, 300.
But the accuracy is not guaranteed.
