### ISSUE TITLE
inference time's Comparison  : original vgg16 vs  cVGG-16_3C4x

### ISSUE THREAD

**Issue by peternara** [yihui-he/channel-pruning#106]
Hi.
I try to finetuning about each imagenet pre-trained model(original vgg16 vs  VGG-16_3C4x) using my new data.
I was successful learning(finetuning) using the channel_pruning_VGG-16_3C4x model you provided.
When referring to only a single image, the inference time is not different from the original model.

"https://github.com/yihui-he/channel-pruning/wiki/inference-time-on-GPU"  is very different from here. Could you tell me why?
@yihui-he

**Comment by yihui-he** [comment]
I don’t know.
