### ISSUE TITLE
tutorial question

### ISSUE THREAD

**Issue by Androsimus** [yihui-he/channel-pruning#107]
Hi!
I'm trying to repeat results on VGG-16. 
I followed the tutorial of "Channel Pruning" section, but after step "Start Channel Pruning" I didn't recieve file "temp/cb_3c_3C4x_mem_bn_vgg.prototxt", which is nessesary for next step. Instead I recieved - 3C4x_mem_bn_vgg.prototxt, 
3c_3C4x_me_m_bn_vgg.prototxt, 
bn_vgg.prototxt,
mem_bn_vgg.prototxt,
3c_vgg.caffemodel,
bn_vgg.caffemodel,
frozen500.pickle,
VH_bn_vgg.caffemodel.

What should I do to get cb_3c_3C4x_mem_bn_vgg.prototxt?

Thank you!

**Comment by yihui-he** [comment]
https://github.com/yihui-he/channel-pruning/blob/master/combine.sh

**Comment by huoguangdiandian** [comment]
> Hi!
> I'm trying to repeat results on VGG-16.
> I followed the tutorial of "Channel Pruning" section, but after step "Start Channel Pruning" I didn't recieve file "temp/cb_3c_3C4x_mem_bn_vgg.prototxt", which is nessesary for next step. Instead I recieved - 3C4x_mem_bn_vgg.prototxt,
> 3c_3C4x_me_m_bn_vgg.prototxt,
> bn_vgg.prototxt,
> mem_bn_vgg.prototxt,
> 3c_vgg.caffemodel,
> bn_vgg.caffemodel,
> frozen500.pickle,
> VH_bn_vgg.caffemodel.
> 
> What should I do to get cb_3c_3C4x_mem_bn_vgg.prototxt?
> 
> Thank you!

这个3c_3C4x_mem_bn_vgg.prototxt文件里路径是怎么设置的，我运行的时候总是出现错误
![image](https://user-images.githubusercontent.com/45250079/64665084-d4f2d880-d483-11e9-8e12-f16ccc45e881.png)
****
