### ISSUE TITLE
has AMC released?

### ISSUE THREAD

**Issue by vincent8877** [yihui-he/channel-pruning#108]
Hi @yihui-he 
   I read your paper <AMC: AutoML for Model Compression and Acceleration on Mobile Devices>, and I am very interesting in AMC because I want to compress MobileNet_SSD.
   I wonder have you released the code/tool/software of AMC? or when you plan to release it? I could not wait to use it.
   Thank you!

**Comment by yihui-he** [comment]
Currently we don't have any open source plan for AMC. But you cat look at PocketFlow https://github.com/Tencent/PocketFlow. 
They implemented both channel pruning and AMC

**Comment by mrocr** [comment]
@yihui-he are you considering releasing `AMC: AutoML` code?

**Comment by yihui-he** [comment]
@mrocr some released models can be found here: https://github.com/mit-han-lab/amc-compressed-models

**Comment by mrocr** [comment]
@yihui-he I am interested in Resnet-50, so I would appreciate it if you release the Resnet-50 models.
Waiting for your reply
