### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by shiruipeng1985** [yihui-he/channel-pruning#110]
All are welcome to create issues, but please google the problem first, and make sure it has not already been reported.

### What hardware and operating system/distribution are you running?
Operating system:  
CUDA version:  
CUDNN version:  
openCV version:  
BLAS:  
Python version:

**Comment by shiruipeng1985** [comment]
Did the resnet50-2x model just be used in GPU model?

**Comment by shiruipeng1985** [comment]
Did the resnet50-2x model just be used in GPU mode?

**Comment by yihui-he** [comment]
yes
