### ISSUE TITLE
Will it be possible to run these models in CPU? What changes to make?

### ISSUE THREAD

**Issue by vinod1993** [yihui-he/channel-pruning#113]
All are welcome to create issues, but please google the problem first, and make sure it has not already been reported.

### What hardware and operating system/distribution are you running?
Operating system:  
CUDA version:  
CUDNN version:  
openCV version:  
BLAS:  
Python version:

**Comment by yihui-he** [comment]
Some layers might only have CPU implementation, which you need to implement yourself.
