### ISSUE TITLE
Deep Neural Network Pruning Tools?

### ISSUE THREAD

**Issue by hammadullah125** [yihui-he/channel-pruning#114]
I am currently working with DeePhi tools (http://www.deephi.com/technology) that are used for pruning and quantization. I searched on internet to find some similar tools for CNN or DNN but couldn't find any. I would appreciate if anybody can suggest me some pruning tools. Thanks in advance.

**Comment by yihui-he** [comment]
https://github.com/Tencent/PocketFlow#channel-pruning
