### ISSUE TITLE
Question about MoBiNet

### ISSUE THREAD

**Issue by hoangminhq5310** [yihui-he/channel-pruning#122]
All are welcome to create issues, but please google the problem first, and make sure it has not already been reported.

### What hardware and operating system/distribution are you running?
Operating system:  
CUDA version:  
CUDNN version:  
openCV version:  
BLAS:  
Python version:  

### If the bug is a crash, provide the backtrace.
Hi! I have just read your paper about the fuse of MobileNet and BNN which is called MoBiNet. In the paper you said that the implemented framework is Pytorch and I am wondering if you have its repository online? If that is true can you share it?
Thank you very much!

**Comment by yihui-he** [comment]
sry, we can't publish the code in the near future.
