### ISSUE TITLE
About the ITQ?

### ISSUE THREAD

**Issue by wspba** [yihui-he/channel-pruning#15]
Hi, could you please tell me the ITQ's full name? I'm not good at math, I searched it in the Internet, but there were nothing. I saw only LASSO in your paper, but SVD, "ITQ" and LASSO in your code, which one makes more contribution? Hope to get your reply, thanks!

**Comment by yihui-he** [comment]
Might be disappointing, ITQ is a nickname I used. It's channel decomposition (Zhang etal) mentioned in paper.

**Comment by yihui-he** [comment]
3 algorithms' contribution is not discussed, which is not our focus. Grossly, VH and channel decomposition contribute 3x, and channel pruning contribute 4/3x
