### ISSUE TITLE
How can I set single channel pruning?

### ISSUE THREAD

**Issue by zlheos** [yihui-he/channel-pruning#16]
first, I really appreciated for your help!
Then I have some quesqions
How can i set single channel pruning?
how much is channel prunning accerate ration ?
why  channel_pruning_VGG-16_3C4x.caffemodel is so big ?

**Comment by yihui-he** [comment]
To use only channel pruning, u need modify the function r3 in net.py. for acceleration ratio, look at paper and code. 
Because it's a 40+ layers network.

**Comment by zlheos** [comment]
sorry to trouble you !
I don't know  how to modify r3 for single channel prunning ? 
thank you very much!

**Comment by yihui-he** [comment]
We currently are not planning to release other parts of code.

**Comment by zlheos** [comment]
Sorry to trouble you !
in R3 function 
why don't prunning conv1_1 ? 
and 
I see pooldic = ['conv1_2', 'conv2_2'] ] , why no 'conv3_3' and others ?
I really appreciated for your help!

**Comment by yihui-he** [comment]
- conv1_1 contributes little computation.
- VH decompose degrades performance when decomposing conv3_3 and later

**Comment by zlheos** [comment]
thank you !
if only CR ,  how much should we set for  c_ratio  parameter ?
and how much should we set for very layer compression ration ?

**Comment by slothkong** [comment]
@zlheos hello. Do you know how to use @yihui-he's code to perform single-layer pruning?
