### ISSUE TITLE
i used python2.7,which need to be modified.i find the file of 'Makefile' have the keywords of 'python3.4' .

### ISSUE THREAD

**Issue by zhaoliang210325** [yihui-he/channel-pruning#17]
All are welcome to create issues, but please google the problem first, and make sure it has not already been reported.

### What hardware and operating system/distribution are you running?
Operating system:  ubuntu 14.04
CUDA version:  8.0
CUDNN version:  5.1
openCV version:  3.1
BLAS:  
Python version:  2.7

**Comment by yihui-he** [comment]
please use python3
