### ISSUE TITLE
/usr/bin/ld: cannot find -lboost_python3

### ISSUE THREAD

**Issue by LearnerInGithub** [yihui-he/channel-pruning#19]
@yihui-he 
All are welcome to create issues, but please google the problem first, and make sure it has not already been reported.

### What steps reproduce the bug?
make clean && make -j32 && make pycaffe -j32

### What hardware and operating system/distribution are you running?
Operating system:  Ubuntu14.04
CUDA version:  cuda-8.0
CUDNN version:  5.1
openCV version:  2.4.9
BLAS:  mkl
Python version:  python3.4

### If the bug is a crash, provide the backtrace.

part error log:
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: cannot find -lboost_python3
collect2: error: ld returned 1 exit status
make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1

**Comment by yihui-he** [comment]
cannot find -lboost_python3.  
You should install boost

**Comment by LearnerInGithub** [comment]
@yihui-he I had installed boost, but it stiil report such problem. So I am wonder how you installed boost for python3?

**Comment by yihui-he** [comment]
please google the problem first, and make sure it has not already been reported.

**Comment by LearnerInGithub** [comment]
@yihui-he I googled it, h=then I followed the advices installed boost-1.59 and 1.63, both not fixed this problem, so I ask question here.

**Comment by yihui-he** [comment]
https://www.google.com/search?q=caffe+cannot+find+lboost+python

**Comment by LearnerInGithub** [comment]
@yihui-he Fixed the problem, the solution is that compile the boost lib by python3 not the python, so it will generate the needed libs.   Thansk for answering!
