### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by LXWDL** [yihui-he/channel-pruning#21]
Hi,thanks for your codes,When I adopt the following configuration, encounter the following error in make test:
Operating system:  linux
CUDA version:  8.0
CUDNN version:  cudnn-8.0-linux-x64-v5.0
openCV version:  3.0
BLAS:  yes
Python version:  3.4
the error is:
src/caffe/test/test_filter_layer.cpp:20:3: error： Uninitialized members‘caffe::FilterLayerTest<caffe::CPUDevice<float> >::blob_top_labels_’Has a 'const' type‘ caffe::Blob<float>* const’ [-fpermissive];
I have no idea how to solver this problom,thanks for your help.

**Comment by yihui-he** [comment]
There's no need for make test
