### ISSUE TITLE
Also using svd method?

### ISSUE THREAD

**Issue by Wenstery** [yihui-he/channel-pruning#23]
From the code, VGG16 acceleration factor can be 3X-4X, not only by using channel-pruning method but also used svd ?  Is it true?

And What about the effect of ssd mobilenet ?

**Comment by yihui-he** [comment]
- It use SVD for spatial decomposition and channel decomposition, please refer to paper for details.
- haven't studied.

**Comment by Wenstery** [comment]
Oh,the paper hasn't described the svd steps, thanks a lot.

**Comment by yihui-he** [comment]
details are in:
- spatial decomposition (Speeding up Convolutional Neural Networks with Low Rank Expansions)
- channel decomposition (Accelerating Very Deep Convolutional Networks for Classification and Detection)
