### ISSUE TITLE
What's mean of WPQ in train.py of c3 function?

### ISSUE THREAD

**Issue by LearnerInGithub** [yihui-he/channel-pruning#24]
@yihui-he in function c3() of train.py, this line(https://github.com/yihui-he/channel-pruning/blob/master/train.py#L73) of code : WPQ, new_pt = net.R3(), I can't find descriptions of WPQ in your paper, could you explain it?

**Comment by yihui-he** [comment]
It stores pruned values, which will be saved to caffemodel later.

**Comment by LearnerInGithub** [comment]
@yihui-he Thanks, seems clear more.
