### ISSUE TITLE
how to deal with the trained model of faster rcnn?(vgg)

### ISSUE THREAD

**Issue by liangzz1991** [yihui-he/channel-pruning#25]
All are welcome to create issues, but please google the problem first, and make sure it has not already been reported.

### What hardware and operating system/distribution are you running?
Operating system:  
CUDA version:  
CUDNN version:  
openCV version:  
BLAS:  
Python version:

**Comment by yihui-he** [comment]
Temporarily, we only release the code for VGG-16 3C 4X, due to non-technical issue. You could implement it yourself by following the paper. 
Duplicate of #11

**Comment by yihui-he** [comment]
https://github.com/yihui-he/channel-pruning#pruning-faster-rcnn
