### ISSUE TITLE
Request: Explanation on how to set the speed-up for each layer independently

### ISSUE THREAD

**Issue by slothkong** [yihui-he/channel-pruning#28]
I've been studying the code you kindly posted, but I'm still unsure on how to set the speed-up factor for the layers, or is it possible to set a specific speed-up factor for the pruning to modify each layer differently. Could you please provide so indications on how to achieve this?

**Comment by yihui-he** [comment]
I wrote a function description: https://github.com/yihui-he/channel-pruning/blob/master/lib/net.py#L1648
it can be achieved by set d_prime
