### ISSUE TITLE
can you share your model(GPU 2.5X)?

### ISSUE THREAD

**Issue by zlheos** [yihui-he/channel-pruning#29]
The pre-model channel_pruning_VGG-16_3C4x is slowly on GPU platform
can you share your 2.5X on GPU?

**Comment by yihui-he** [comment]
I failed to find the 4x caffemodel. 5x is released.

**Comment by zlheos** [comment]
great great great job! 
thank you for your share!!!

**Comment by zlheos** [comment]
can you share your channel pruning code ?
