### ISSUE TITLE
undefined reference to 'nccl*****'

### ISSUE THREAD

**Issue by eeric** [yihui-he/channel-pruning#3]
only one GPU, so it was shut to NCCL multi GPUs, error as following:

Makefile:631: recipe for target '.build_release/examples/mnist/convert_mnist_data.bin' failed
make: *** [.build_release/examples/mnist/convert_mnist_data.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `ncclGetUniqueId'
.build_release/lib/libcaffe.so: undefined reference to `ncclBcast'
.build_release/lib/libcaffe.so: undefined reference to `ncclAllReduce'
.build_release/lib/libcaffe.so: undefined reference to `ncclCommInitRank'
.build_release/lib/libcaffe.so: undefined reference to `ncclCommDestroy'
.build_release/lib/libcaffe.so: undefined reference to `ncclCommInitAll'
.build_release/lib/libcaffe.so: undefined reference to `ncclGetErrorString'
collect2: error: ld returned 1 exit status
Makefile:626: recipe for target '.build_release/tools/extract_features.bin' failed
make: *** [.build_release/tools/extract_features.bin] Error 1

**Comment by yihui-he** [comment]
This is a caffe building problem I haven't met before. I guest it's because your NCCL is not linked. Is there a `/usr/lib/libnccl.so` in your system?

**Comment by eeric** [comment]
ye, there was no libnccl.so.
one hand,only one GPU, so it was shut to NCCL multi GPUs, it occured error above when executing script that make -j8.

**Comment by yihui-he** [comment]
Two option:
- install nccl and make sure it is linked (`/usr/lib/libnccl.so`)
- disable nccl in `makefile.config` (https://github.com/yihui-he/caffe-pro/blob/3905e14005fddf1be74148cc1c65a755531a546c/Makefile.config#L16, haven't tried this one)

**Comment by eeric** [comment]
the 2nd option was chosen.
