### ISSUE TITLE
Nonuniform GPU accelerate ration?

### ISSUE THREAD

**Issue by zlheos** [yihui-he/channel-pruning#31]
The reference paper[53]: <Accelerating Very Deep Convolutional Networks for Classification and detection>
there exists a nonuniform result

> asym. (3d) model give  (3.0×) GPU accelerate in Tabel 8
> but it show 0.96X GPU accelerate in your paper in Tabel 3

why is so big different?

**Comment by yihui-he** [comment]
As our paper indicate, this is because CUDA and CUDNN upgrade

**Comment by zlheos** [comment]
which cuda / cudnn version realize 3.0X GPU accelerate ? @yihui-he

**Comment by yihui-he** [comment]
Just search 'cuda' in the paper's PDF
