### ISSUE TITLE
About the VGG16 baseline accuracy in paper

### ISSUE THREAD

**Issue by MingSun-Tse** [yihui-he/channel-pruning#45]
Thx for opening your impressive work. 
In your paper, for `1-view, baseline 89.9%` of VGG16, is this result from the open caffemodel offered by [VGG group](http://www.robots.ox.ac.uk/~vgg/software/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel)?

**Comment by yihui-he** [comment]
There's baidu yun, see readme.
From our server.

Best,
Yihui He

________________________________
