### ISSUE TITLE
imageNet

### ISSUE THREAD

**Issue by cicido** [yihui-he/channel-pruning#48]
Operating system:  CentOS7
CUDA version:  8.0
CUDNN version:  6.0
openCV version:  2.4.5
BLAS:  open
Python version:  3.6.1
I want to know the data url
https://pan.baidu.com/s/1dDizyed#list/path=%2FImageNet
is good for use?

**Comment by cicido** [comment]
@yihui-he 你发的那个imageNet下载地址，需要审核，有没有其他可用的数据源？

**Comment by yihui-he** [comment]
I don't know
