### ISSUE TITLE
how to calculate the speedup in paper?

### ISSUE THREAD

**Issue by MingSun-Tse** [yihui-he/channel-pruning#50]
I'm reimplementing the paper, confused about the speedup setting. The paper compares different methods under different speedup settings like "2x, 4x, 5x". I'm curious about how to calculate that. 
1. My understanding is, "2x" means `GFLOPs of all conv layers before prune / GFLOPs of all conv layers after prune = 2`, is this correct?
2. I download the supplied [caffemodels and net prototxts](https://github.com/yihui-he/channel-pruning/releases), and calculate the GFLOPs of `VGG-16 3C4x` and `channel pruning 5X `. Here is the result:
with a 224x224x3 image as input,
- the total conv GFLOPs of original unpruned VGG16 net is 15.3466
- the total conv GFLOPs of `VGG-16 3C4x` is 4.6145
- the total conv GFLOPs of `channel pruning 5X ` is 3.3917
namely, the speedup in my understanding is `15.3466/4.6145=3.3` and `15.3466/3.3917=4.5`, which is quite different from the paper's report. Did I miss something, anyone can help?

**Comment by yihui-he** [comment]
use `calflop.sh` to compute flops

**Comment by juliagusak** [comment]
@MingSun-Tse, did you succeed in getting  5x instead of 4.5x using calflops.sh?

**Comment by MingSun-Tse** [comment]
> @MingSun-Tse, did you succeed in getting 5x instead of 4.5x using calflops.sh?

Out of laziness, I did not check that script... I probably will run it in a few days. Then I will report the result here. Plus, if you get some results, welcome to share them :-).

**Comment by juliagusak** [comment]
Hey @MingSun-Tse,

that would be great if you report your experimental results here!)

If I understand  the code correctly (```calflops.sh```,  ```flops() ``` from ``` tools.py``` and ```layercomputation(), computation() ``` from ```lib/net.py```), "nx"-speedup reported in the paper is a ratio of FLOPs before to FLOPs after  pruning, i.e. exactly how you described it  in  your first message. And yeah, FLOPs are computed only for convolutional layers.

I've implemented the same FLOPs counting in PyTorch and same as you obtained  ```4.1``` and ```4.52``` "nx"-speedup values for  released [4x and 5x  VGG16](https://github.com/yihui-he/channel-pruning/releases) classification models (to be precise, for their PyTorch versions obtained via [MMdnn](https://github.com/Microsoft/MMdnn))

Also, for  4x and  5x  VGG16 Caffe models I've measured an absolute forward time using ```timeit ``` and got the following  absolute acceleration:
```
CPU (batch size = 1):  2.24,  2.95
GPU (batch size = 32): 2.17,  3.44
  ```
So, in my experiments real speed up is much lower than the theoretical one computed based on FLOPs of conv layers...

@yihui-he, could you, please, confirm whether we understand correctly your definition of "nx"-speedup? Thanks!

**Comment by zeyu-liu** [comment]
> Hey @MingSun-Tse,
> 
> that would be great if you report your experimental results here!)
> 
> If I understand the code correctly (`calflops.sh`, `flops() ` from ` tools.py` and `layercomputation(), computation() ` from `lib/net.py`), "nx"-speedup reported in the paper is a ratio of FLOPs before to FLOPs after pruning, i.e. exactly how you described it in your first message. And yeah, FLOPs are computed only for convolutional layers.
> 
> I've implemented the same FLOPs counting in PyTorch and same as you obtained `4.1` and `4.52` "nx"-speedup values for released [4x and 5x VGG16](https://github.com/yihui-he/channel-pruning/releases) classification models (to be precise, for their PyTorch versions obtained via [MMdnn](https://github.com/Microsoft/MMdnn))
> 
> Also, for 4x and 5x VGG16 Caffe models I've measured an absolute forward time using `timeit ` and got the following absolute acceleration:
> 
> ```
> CPU (batch size = 1):  2.24,  2.95
> GPU (batch size = 32): 2.17,  3.44
> ```
> 
> So, in my experiments real speed up is much lower than the theoretical one computed based on FLOPs of conv layers...
> 
> @yihui-he, could you, please, confirm whether we understand correctly your definition of "nx"-speedup? Thanks!

Generally, FLOPs is not equal to the actual latency.
