### ISSUE TITLE
Channel-pruning: Why deleted W2 weights are simply set to 0 (not removed; W2.shape remains the same) ?

### ISSUE THREAD

**Issue by slothkong** [yihui-he/channel-pruning#51]
In `'''channel pruning''' `, `dictionary_kernels()` gives the result of the feature map selection (i.e.  indices,  weights and  bias):
https://github.com/yihui-he/channel-pruning/blob/c18d5ae4f8dd895e22d89a388f13630d1220876a/lib/net.py#L1440-L1445

As you know, using the indices(`idxs`), the values of `W2` that aren't selected are set to zero , while the selected are over-written with `W2.copy()` *(`W2`** shape remains the same)*.

But in case of `W1`, un-selected filters are completely vanished from the WPQ dictionary:
https://github.com/yihui-he/channel-pruning/blob/c18d5ae4f8dd895e22d89a388f13630d1220876a/lib/net.py#L1452-L1454

Why? I'm assuming that it is OK because in the next iteration  `convnext` will be labeled as `conv` , and the weights that were set as zero will be selected by the lasso regression to be removed (so it takes 2 iterations to vanish a set of filter). Am I correct?

**Comment by slothkong** [comment]
Seem like the W2 weights that were selected are dropped at the beginning of the next iteration, at the start of `'''spatial decomposition'''`. But in this case I still don't know why set them to 0 before removing them from the actual model.

**Comment by yihui-he** [comment]
#channels in caffe model could not be dynamical changed
