### ISSUE TITLE
Is the method just shrink the channel size(find the best channel size)?

### ISSUE THREAD

**Issue by lcytzk** [yihui-he/channel-pruning#53]
After I go through the whole paper, if I understand right, the whole method is just to optimize a formula which will get a beta(0-1 vector) and W'(which changed from W). As the c' seems like given by human beings, so I wonder if I just pick a less channel number and do training, will I get convergence?

In other words, the method is to find a better channel number for every layer of a model, am I right?
If that is true, can I just set channel number as a less one to do the trainning? What's the difference?

Thank you for your paper, and I hope someone can help me solve my question.

**Comment by yihui-he** [comment]
See compared with training section

Best,
Yihui He

________________________________
