### ISSUE TITLE
Help on understanding the code

### ISSUE THREAD

**Issue by zuowang** [yihui-he/channel-pruning#55]
I am debugging you code, and found it's hard to figure out why newX.dot(W2) not equal to gtY exactly? Could you help me on this? Great Thanks!
       print("rMSE", rel_error(newX.reshape((newX.shape[0],-1)).dot(W2.reshape((W2.shape[0],-1)).T), gtY))

**Comment by slothkong** [comment]
@zuowang I think in the first iteration they will be same, but as the loop progress weights are modified (prune weights are replaced with zeros.) So computing the activation of some sampled points of the layer no longer gives the initial, hence the mean squared error calculation. I didint write the code thought, so please don't think I'm 100% correct

**Comment by zuowang** [comment]
It make sense. Thanks a lot!
