### ISSUE TITLE
layer还是layer.name

### ISSUE THREAD

**Issue by cicido** [yihui-he/channel-pruning#56]
在看builder.py代码， 一个layer有四个属性，name, type, top, bottom.
name,type应该是str类型
top, bottom为list类型，但其元素类型是str类型还是layer？

**Comment by cicido** [comment]
另一个问题：
我在builder.py大量看到：
new_layer = self.net.layer.add()
new_param = self.this.param.add()
等这样的add操作，是python哪个语法点？

**Comment by yihui-he** [comment]
这些全是protobuf的语法
