### ISSUE TITLE
can i compile the code with python2

### ISSUE THREAD

**Issue by zhangyunming** [yihui-he/channel-pruning#57]
when i compile the caffe with python3,it is ok,but when i"import caffe",it has some bug ,so,can the code compile with python2,how?

**Comment by Betterthinking** [comment]
I tried compile with python2.7 before but there appear to be many syntax error, so you'd better compile with python3. The 'import caffe' error may be a result of wrong PYTHONPATH variable, try to export PYTHONPATH to be your caffe's python folder, maybe it works.

**Comment by yihui-he** [comment]
python2  is not tested in our code before. 
Use at your own risk.
