### ISSUE TITLE
End-to-End Pruning for Detections?

### ISSUE THREAD

**Issue by GBJim** [yihui-he/channel-pruning#59]
Hi 
The current acceleration for Faster-RCNN is to prune VGG-16 as the pre-trained model for the whole detection net.
Is it possible to prune Faster-RCNN or other detection networks End-to-End on data like Pascal VOC?

**Comment by yihui-he** [comment]
Of course, you can. Our approach is unsupervised. 
You only need to feed VOC images into it.
But I guess the feature sampling strategy should not be random anymore.
Sampling according to objects location might be better.
Minimizing error on background feature makes no sense.

**Comment by GBJim** [comment]
@yihui-he Thank you for answering!
