### ISSUE TITLE
experiment: error: unrecognized arguments: -gpu GPU0

### ISSUE THREAD

**Issue by eeric** [yihui-he/channel-pruning#6]
python3 train.py -action c3 -gpu GPU0
usage: experiment [-h] [-tf TF_VIS] [-caffe CAFFE_VIS] [-action ACTION]
                  [-dic.keep DICDOTKEEP] [-dic.vh DICDOTVH]
                  [-dic.fitfc DICDOTFITFC] [-dic.rank_tol DICDOTRANK_TOL]
                  [-dic.afterconv DICDOTAFTERCONV]
                  [-dic.prepooling DICDOTPREPOOLING] [-dic.debug DICDOTDEBUG]
                  [-dic.option DICDOTOPTION]
                  [-dic.layeralpha DICDOTLAYERALPHA] [-dic.alter DICDOTALTER]
                  [-an.l1 ANDOTL1] [-an.l2 ANDOTL2] [-an.ratio ANDOTRATIO]
                  [-an.filter ANDOTFILTER] [-res.bn RESDOTBN]
                  [-res.short RESDOTSHORT] [-nPointsPerLayer NPOINTSPERLAYER]
                  [-nofc NOFC] [-ls LS] [-autodet AUTODET] [-fc_reg FC_REG]
                  [-kernelname KERNELNAME] [-data DATA] [-Action ACTION]
                  [-ntest NTEST] [-nBatches_fc NBATCHES_FC] [-solver SOLVER]
                  [-prototxt PROTOTXT] [-nBatches NBATCHES] [-model MODEL]
                  [-fc_ridge FC_RIDGE] [-nonlinear_fc NONLINEAR_FC]
                  [-frozen FROZEN] [-splitconvrelu SPLITCONVRELU]
                  [-weights WEIGHTS] [-mp MP] [-log LOG] [-shm SHM]
experiment: error: unrecognized arguments: -gpu GPU0
no lighting pack
How to work?

**Comment by yihui-he** [comment]
Sorry, it's a typo. It should be `python3 train.py -action c3 -caffe GPU0` instead.

**Comment by eeric** [comment]
how to set GPU0, beause there was only one GPU

**Comment by yihui-he** [comment]
0
