### ISSUE TITLE
what's means?

### ISSUE THREAD

**Issue by eeric** [yihui-he/channel-pruning#7]
>>caffe test -model ****.prototxt -weights ****.caffemodel -iterations 5 -gpu GPU0
>>terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_lexical_cast> >'
  what():  bad lexical cast: source type value could not be interpreted as target
*** Aborted at 1503819237 (unix time) try "date -d @1503819237" if you are using GNU date ***
PC: @     0x7f477dd6e1c7 gsignal
*** SIGABRT (@0x3ea00005f02) received by PID 24322 (TID 0x7f477fe20740) from PID 24322; stack trace: ***
    @     0x7f477dd6e250 (unknown)
    @     0x7f477dd6e1c7 gsignal
    @     0x7f477dd6fe2a abort
    @     0x7f477e3a9b7d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f477e3a79c6 (unknown)
    @     0x7f477e3a7a11 std::terminate()
    @     0x7f477e3a7c29 __cxa_throw
    @           0x410154 boost::throw_exception<>()
    @           0x409612 get_gpus()
    @           0x40a29d test()
    @           0x4084e0 main
    @     0x7f477dd59ac0 __libc_start_main
    @           0x408d09 _start
    @                0x0 (unknown)
Aborted (core dumped)

**Comment by yihui-he** [comment]
I think you should replace GPU0 with your actual gpu device like 0,1,2 or 3

**Comment by eeric** [comment]
there was only one GPU, how to set?

**Comment by yihui-he** [comment]
you should set 0.
