### ISSUE TITLE
Problems about the first step of channel pruning

### ISSUE THREAD

**Issue by cqwwww** [yihui-he/channel-pruning#74]
When I start channel pruning, the process has stayed at satge1 all the time. And it shows _The total number of bytes read was 537226272_. But it is strange that the program does not report any error. I doubt whether I should wait for the program until it continues running, or there may be something wrong with my procedure.

**Comment by yihui-he** [comment]
Do you have enough memory like 64G?

**Comment by yihui-he** [comment]
Duplicate of #37
