### ISSUE TITLE
Can it use on PyTorch's model?

### ISSUE THREAD

**Issue by RichardMrLu** [yihui-he/channel-pruning#77]
Pytorch save model as xxx.pth

**Comment by yihui-he** [comment]
Now tensorflow is supported:
you can look at PocketFlow.
They implemented both channel pruning and [AMC](http://openaccess.thecvf.com/content_ECCV_2018/html/Yihui_He_AMC_Automated_Model_ECCV_2018_paper.html). They have results on MobileNets.
