### ISSUE TITLE
collision

### ISSUE THREAD

**Issue by eeric** [yihui-he/channel-pruning#8]
it conflicted when implementing both make pycaffe with cmake .. && make, then it didn't work to import caffe.

**Comment by yihui-he** [comment]
I didn't understand this question. Where do we need cmake?

**Comment by eeric** [comment]
should to generate caffe script first, then make pycaffe.

**Comment by yihui-he** [comment]
If you could not import caffe in python, it mostly caused by pycaffe not in PYTHONPATH. You should google it for more details.
