### ISSUE TITLE
how can i Turn   cb_3c_3C4x_mem_bn_vgg.prototxt   into    channel_pruning.prototxt ?

### ISSUE THREAD

**Issue by alexqiaodan** [yihui-he/channel-pruning#80]
how can i Turn   cb_3c_3C4x_mem_bn_vgg.prototxt   into    channel_pruning.prototxt ?

**Comment by alexqiaodan** [comment]
how can i turn cb_3c_3C4x_mem_bn_vgg.prototxt into channel_pruning.prototxt ?

**Comment by yihui-he** [comment]
Duplicate of #16
