### ISSUE TITLE
processing time for channel-pruning

### ISSUE THREAD

**Issue by ryusaeba** [yihui-he/channel-pruning#82]
Hi @yihui-he, 

Thanks for the sharing. Could you please share the processing time for channel-pruning? 
For example, 
How long do you need for VGG-16, i.e from VGG-16 without pruning to VGG-16 with channel pruning and finetune. 

Thanks

**Comment by yihui-he** [comment]
![time](https://user-images.githubusercontent.com/10027339/35959272-d92a4a04-0cdf-11e8-8e48-866f933e0a08.png)

Finetuning takes 1/10 of the original number of epochs.
