### ISSUE TITLE
ResNet-50-2X  Inference time larger than original ResNet50?

### ISSUE THREAD

**Issue by HeavySword** [yihui-he/channel-pruning#88]
@yihui-he 
According my tests, ResNet-50-2X Inference time is not smaller but significantly larger than ori ResNet50!
I found "Filter"layer spends too much time, about 2~4ms/per filter layer with Titan Xp
"(sampler) Computational cost for this operation could 
be ignored." -- Your paper said.

Any thing wrong with my test? thank!

**Comment by yihui-he** [comment]
Filter layer is not well implemented. In theory, computational cost for this operation could be ignored.

**Comment by shiruipeng1985** [comment]
@HeavySword I have the same problem, the ResNet-50-2X inference time need 0.1s on gtx1060, but the ori ResNet50 just need 0.04s! Did you solve this problem?
