### ISSUE TITLE
error == cudaSuccess (38 vs. 0) no CUDA-capable device is detected

### ISSUE THREAD

**Issue by young-fire** [yihui-he/channel-pruning#89]
All are welcome to create issues, but please google the problem first, and make sure it has not already been reported.

### What steps reproduce the bug?
run python3 train.py -action c3 -caffe [GPU0] ,the error appear as follows!

### What hardware and operating system/distribution are you running?
no lighting pack
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0303 09:50:12.085932 3744 common.cpp:152] Check failed: error == cudaSuccess (38 vs. 0) no CUDA-capable device is detected

Operating system:  ubuntu 16.04
CUDA version:  8.0
CUDNN version:  v6
openCV version:  3.2.0
BLAS:  
Python version:  3.5

**Comment by wangjx123** [comment]
Do you solve this problem? @young-fire
