### ISSUE TITLE
Check failed: !lines_.empty() File is empty

### ISSUE THREAD

**Issue by eeric** [yihui-he/channel-pruning#9]
$ python3 train.py -action c3 -caffe 0
no lighting pack
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0828 09:45:42.791590 17829 image_data_layer.cpp:53] Check failed: !lines_.empty() File is empty
*** Check failure stack trace: ***

$ python3 train.py -action c3 -caffe GPU0
no lighting pack
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0828 09:46:49.385843 17904 common.cpp:152] Check failed: error == cudaSuccess (38 vs. 0)  no CUDA-capable device is detected
*** Check failure stack trace: ***

how to do?

**Comment by yihui-he** [comment]
`image_data_layer.cpp:53] Check failed: ` 
This means you didn't set image data path or mean image path.

**Comment by eeric** [comment]
ye, so how to set image data path?

**Comment by yihui-he** [comment]
Read the readme carefully.

Download ImageNet classification dataset http://www.image-net.org/download-images
Specify imagenet source path in temp/vgg.prototxt (line 12 and 36)
