### ISSUE TITLE
 Message type "caffe.ImageDataParameter" has no field named "new_dim"

### ISSUE THREAD

**Issue by zhao1995** [yihui-he/channel-pruning#90]
All are welcome to create issues, but please google the problem first, and make sure it has not already been reported.

### What hardware and operating system/distribution are you running?
Operating system:  Ubuntu 14.04
CUDA version:  8.0
CUDNN version:  5.1
openCV version:  2.4.13
BLAS:  atlas
Python version:  3.4

### If the bug is a crash, provide the backtrace.

After compile,i run :

caffe test -model channel_pruning_VGG-16_3C4x/channel_pruning_VGG-16_3C4x.prototxt -weights channel_pruning_VGG-16_3C4x/channel_pruning_VGG-16_3C4x.caffemodel -iterations 5000 -gpu 0

then the result is:

I0316 16:32:38.900554 31805 caffe.cpp:261] Use GPU with device ID 0
I0316 16:32:38.901036 31805 caffe.cpp:265] GPU device name: GeForce GTX 1060 3GB
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 18:12: Message type "caffe.ImageDataParameter" has no field named "new_dim".
F0316 16:32:39.191406 31805 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: channel_pruning_VGG-16_3C4x/channel_pruning_VGG-16_3C4x.prototxt
*** Check failure stack trace: ***
    @     0x7f994cfeddbd  google::LogMessage::Fail()
    @     0x7f994cfefc5d  google::LogMessage::SendToLog()
    @     0x7f994cfed9ac  google::LogMessage::Flush()
    @     0x7f994cff057e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f994d6ac7de  (unknown)
    @     0x7f994d68b558  (unknown)
    @           0x4099e4  (unknown)
    @           0x40867c  (unknown)
    @     0x7f994bad9f45  (unknown)
    @           0x408e4d  (unknown)
Aborted (core dumped)

**Comment by Jinyyyy** [comment]
I have the same problem. Please tell me the solution if you solve this problem. The strange thing is the first time I can run the caffe test, but when I want to reproduce the result, this problem comes out.

**Comment by young-fire** [comment]
you should use the author's caffe

**Comment by yihui-he** [comment]
@young-fire is right.

**Comment by donghn** [comment]
> you should use the author's caffe

can you tell me what is the author's Caffe version? And How can I install it? I searched google but I can't find the answers.
