### ISSUE TITLE
Excuse me, is there any version that support tensorflow ?

### ISSUE THREAD

**Issue by LouiValley** [yihui-he/channel-pruning#93]
Exceuse me, as I see, it implements under caffe. If I wanna prune some networks which is run under tensorflow implementation, is there any version that support tensorflow ?

**Comment by young-fire** [comment]
I want to do this , but need help.

**Comment by yihui-he** [comment]
You might be interested in pocketflow, which is implemented using tensorflow.
They implemented both channel pruning and [AMC](http://openaccess.thecvf.com/content_ECCV_2018/html/Yihui_He_AMC_Automated_Model_ECCV_2018_paper.html).
https://github.com/Tencent/PocketFlow#channel-pruning
