### ISSUE TITLE
After channel pruning , a new net deploy.prototxt will be generated?

### ISSUE THREAD

**Issue by gengwb** [yihui-he/channel-pruning#99]
All are welcome to create issues, but please google the problem first, and make sure it has not already been reported.

### What hardware and operating system/distribution are you running?
Operating system:  
CUDA version:  
CUDNN version:  
openCV version:  
BLAS:  
Python version:

**Comment by yihui-he** [comment]
Yes. Actually we use a new prototxt for deploy, test and train is generated.
